/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-12 at 09:34:55 UTC 
 * Modify at your own risk.
 */

package com.appspot.aledana_ep.aledanaapi.model;

/**
 * Model definition for AledanaEndpointsGetAvailabilityResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the aledanaapi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AledanaEndpointsGetAvailabilityResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("avail_color")
  private java.lang.String availColor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("avail_message")
  private java.lang.String availMessage;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAvailColor() {
    return availColor;
  }

  /**
   * @param availColor availColor or {@code null} for none
   */
  public AledanaEndpointsGetAvailabilityResponse setAvailColor(java.lang.String availColor) {
    this.availColor = availColor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAvailMessage() {
    return availMessage;
  }

  /**
   * @param availMessage availMessage or {@code null} for none
   */
  public AledanaEndpointsGetAvailabilityResponse setAvailMessage(java.lang.String availMessage) {
    this.availMessage = availMessage;
    return this;
  }

  @Override
  public AledanaEndpointsGetAvailabilityResponse set(String fieldName, Object value) {
    return (AledanaEndpointsGetAvailabilityResponse) super.set(fieldName, value);
  }

  @Override
  public AledanaEndpointsGetAvailabilityResponse clone() {
    return (AledanaEndpointsGetAvailabilityResponse) super.clone();
  }

}
